Create class to store the EA components
tamirho/evo-delivery pull request #17
Opened 2022-03-20 19:14 UTC by yuval-ya

I didn't finish it but you can put ur suggestion (as a comment or commit)

2022-03-20 20:23 UTC, tamirho commented on ea-engine/main.py
> +    best_individual = tools.selBest(result, k=1)[0]
Let's consider also encapsulating this functionality in the `EA` class as a further task.

2022-03-20 20:28 UTC, tamirho commented on ea-engine/main.py
> +        .create_population(100)
like that

2022-03-20 20:32 UTC, tamirho commented on ea-engine/ea.py
> +        return self
Why this is not a part of `eval_mode`?
Maybe we should change this to `set_population` as all other parameters, and initial the population in the eval mode?

2022-03-20 20:38 UTC, tamirho requested changes
It looks really good!
I think we should consider setting default values to parameters and letting the user set them with setters (as you did) but leave the construction part to the `eval` method or add a new `build` method.

2022-03-20 20:41 UTC, yuval-ya commented
> 
I get your idea.

2022-03-21 12:21 UTC, vladib6 approved these changes
Hi all, I still trying to learn python syntax.

2022-03-21 22:56 UTC, tamirho approved these changes

2022-03-22 13:30 UTC, merged